
services:
  app:
    build: .
    ports:
      - "1402:1402"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/firewallweb
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Dspring.profiles.active=docker
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=firewallweb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
