name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven
      run: |
        # Make mvnw executable
        chmod +x ./mvnw
        # Build project
        ./mvnw clean compile test
    
    - name: Run tests
      run: ./mvnw test
    
    - name: Build JAR
      run: |
        # Make mvnw executable (if not already done)
        chmod +x ./mvnw
        # Build JAR
        ./mvnw clean package -DskipTests
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firewallweb-jar
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: firewallweb-jar
        path: target/
    
    - name: Deploy to server (example)
      run: |
        echo "Deploy step - customize this for your deployment target"
        echo "You can deploy to:"
        echo "- Heroku"
        echo "- AWS"
        echo "- DigitalOcean"
        echo "- Your own server"
        echo "Build artifacts are available in target/ directory"
